#
# Makefile for the Goodix gt9xx touchscreen driver.
#
#subdir-ccflags-y += -DDEBUG
obj-$(CONFIG_TOUCHSCREEN_GT9XX_D9)	+= gt9xx.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_D9)	+= gt9xx_update.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_D9)	+= goodix_tool.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_D9)	+= gt9xx_selftest.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_D9)	+= test_function.o
