#
# Makefile for the focaltech touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_D9)	+=  focaltech_core.o
obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_D9)	+=  focaltech_i2c.o

